(() => {
    const icon = name => window.ICONS[name] || '';
    const status = () => `<div class="status"><span>9:41</span><span class="island"></span><div class="status-icons">${icon('Signal')}${icon('Wifi')}${icon('BatteryFull')}</div></div>`;
    const avatar = (s, mini = false) => `<div class="avatar ${mini ? 'mini' : ''}">${s}</div>`;
    const top = (title, greeting = 'Good morning, Dhairya') => `<div class="topline"><div><div class="greeting">${greeting}</div><h2>${title}</h2></div>${avatar('DP')}</div>`;
    const formTop = () => `<div class="topline"><button class="circle-btn" data-demo="Back to overview" aria-label="Back">${icon('ArrowLeft')}</button><span class="center-title">Add expense</span><button class="circle-btn" data-demo="Expense draft closed" aria-label="Close">${icon('X')}</button></div>`;
    const title = (name, link = 'See all') => `<div class="section-title"><h3>${name}</h3><span class="text-link">${link}</span></div>`;
    const row = (ico, name, sub, amt, foot = '', color = '') => `<div class="row"><div class="row-icon">${icon(ico)}</div><div class="row-main"><div class="row-title">${name}</div><div class="row-sub">${sub}</div></div><div class="row-amount ${color}">${amt}${foot ? `<small>${foot}</small>` : ''}</div></div>`;
    const nav = (active = 'Home') => `<nav class="bottom-nav" aria-label="App navigation">${[['House', 'Home'], ['ReceiptText', 'Expenses'], ['Plus', 'Add'], ['Users', 'Groups'], ['CircleUserRound', 'You']].map(([i, t]) => t === 'Add' ? `<button class="nav-add" data-demo="Open the Add expense screen beside this one" aria-label="Add expense">${icon(i)}</button>` : `<button class="nav-item ${active === t ? 'active' : ''}" data-demo="${t} preview"><span>${icon(i)}</span>${t}</button>`).join('')}<div class="homebar"></div></nav>`;
    const segment = (group = false) => `<div class="segmented"><button class="${group ? '' : 'selected'}" data-segment>Personal</button><button data-segment>1-on-1</button><button class="${group ? 'selected' : ''}" data-segment>Group</button></div>`;
    const categories = () => `<div class="field-label">CATEGORY</div><div class="categories">${[['Utensils', 'Food'], ['Car', 'Travel'], ['ShoppingBag', 'Shopping'], ['MoreHorizontal', 'Other']].map(([i, t], n) => `<button class="category ${n === 0 ? 'selected' : ''}" data-category>${icon(i)}${t}</button>`).join('')}</div>`;
    const field = (i, text, end = '') => `<div class="field">${icon(i)}<span>${text}</span>${end ? `<span class="end">${end}</span>` : ''}</div>`;
    const keypad = () => `<div class="keypad">${['1', '2', '3', '4', '5', '6', '7', '8', '9', '.', '0', 'Delete'].map(n => `<button data-key="${n}" aria-label="${n === 'Delete' ? 'Delete last digit' : n}">${n === 'Delete' ? icon(n) : n}</button>`).join('')}</div>`;
    const amount = (val = '480') => `<div class="amount-entry"><div class="label">${val === '2,400' ? 'Total paid by you' : 'How much did you spend?'}</div><div class="value"><span>₹</span><b data-amount style="font-weight:inherit">${val}</b></div><div class="subtle">INR · Indian Rupee</div></div>`;
    const formFoot = (label = 'Save expense') => `<div class="form-footer"><button class="cta" data-save>${icon('Check')}${label}</button><div class="homebar"></div></div>`;
    const summary = () => `<div class="summary-grid"><div class="small-card"><span class="subtle">${icon('ArrowDownLeft')}You are owed</span><strong class="positive">₹2,450</strong></div><div class="small-card"><span class="subtle">${icon('ArrowUpRight')}You owe</span><strong>₹850</strong></div></div>`;
    const recent = () => `${row('Coffee', 'Blue Tokai', 'Today · Food & drinks', '−₹280')}${row('Car', 'Uber ride', 'Today · Travel', '−₹200')}${row('Utensils', 'Dinner at Social', 'Yesterday · Weekend crew', '−₹600', 'Your share')}`;
    const line = () => `<svg class="line-chart" viewBox="0 0 296 58" fill="none" aria-label="Spending trend"><path d="M0 48L24 39L49 44L73 26L99 34L124 20L148 29L174 11L198 17L223 6L249 15L272 9L296 2" stroke="currentColor" stroke-width="2"/><path d="M0 57H296" stroke="currentColor" opacity=".2" stroke-dasharray="3 4"/></svg>`;
    const people = () => `<div class="members">${avatar('DP', true)}${avatar('AK', true)}${avatar('MR', true)}${avatar('RS', true)}<span>You + 3 friends</span></div>`;
    const groupTop = () => `<div class="topline"><button class="circle-btn" aria-label="Back to groups" data-demo="Back to groups">${icon('ArrowLeft')}</button><span class="center-title">Group details</span><button class="circle-btn" aria-label="Group options" data-demo="Group options preview">${icon('MoreHorizontal')}</button></div>`;
    const cover = (name = 'Weekend crew', sub = 'Good company. Shared expenses.', ico = 'Mountain') => `<div class="group-cover"><div class="cover-head"><div class="row-icon">${icon(ico)}</div><span class="badge">${icon('Users')}4 members</span></div><h2>${name}</h2><p>${sub}</p>${people()}</div>`;
    const balance = () => `<div class="balance-banner"><div><span class="subtle">You are owed in this group</span><strong class="positive">₹1,800</strong></div><button data-demo="Settlement preview · Arjun owes you ₹600">Settle up</button></div>`;
    const groupRows = () => `${row('Utensils', 'Dinner at Social', 'You paid ₹2,400 · split equally', '+₹1,800', 'You lent', 'positive')}${row('Car', 'Cab back home', 'Arjun paid ₹800 · settled', '₹200', 'Your share')}${row('Coffee', 'Coffee catch-up', 'Meera paid ₹600 · settled', '₹150', 'Your share')}`;
    function emeraldHome() { return `${top('A clearer picture.')}<div class="hero"><div class="hero-label">Your spend this month<span class="month">September ⌄</span></div><div class="hero-value">₹18,640<span style="font-size:23px;letter-spacing:-1px">.00</span></div><span class="subtle">Personal + your share of group expenses</span>${line()}<div class="hero-foot">${icon('TrendingDown')}12% less than last month, same period</div></div>${summary()}${title('Recent activity')}${recent()}`; }
    function paperHome() { return `${top('The everyday.', 'THURSDAY, 10 SEPTEMBER')}<div class="hero"><div class="hero-label">September / Your spending${icon('ArrowUpRight')}</div><div class="hero-value">₹18,640<span style="font-size:27px">.00</span></div><span class="subtle">A little here, a little there. All accounted for.</span><div class="hero-foot">${icon('TrendingDown')}Down 12% from the same period in August</div></div>${summary()}<div class="editorial-split"><div class="ring"></div><div class="legend"><b>Where it went</b><br><i></i>Food & drinks · 42%<br><i style="background:#d1b575"></i>Travel · 25%<br><i style="background:#bec9ac"></i>Shopping + other · 33%</div></div>${title('Latest entries', 'View ledger')}${row('Coffee', 'Blue Tokai', '10 Sep / Personal', '₹280.00')}${row('Utensils', 'Dinner at Social', '09 Sep / Your share', '₹600.00')}`; }
    function togetherHome() { return `${top('Life adds up.', 'Hey Dhairya 👋')}<div class="hero"><div class="hero-label">Your September so far<span class="badge">${icon('CalendarDays')}Sep</span></div><div class="hero-value">₹18,640</div><div class="hero-foot">A month of little things & good company.</div></div>${summary()}${title('Your people', 'All friends')}<div class="friend-strip">${[['AK', 'Arjun'], ['MR', 'Meera'], ['RS', 'Riya'], ['Plus', 'Invite']].map(([s, n]) => `<div class="friend-item"><div class="avatar">${s === 'Plus' ? icon('Plus') : s}</div>${n}</div>`).join('')}</div>${title('Shared with love', 'All groups')}<div class="group-tile"><div class="row-icon">${icon('Mountain')}</div><div class="row-main"><strong>Weekend crew</strong><div class="row-sub">4 friends · 8 expenses<br><span style="color:#536f45">You get back ₹1,800</span></div></div>${icon('ChevronRight')}</div><div class="group-tile"><div class="row-icon" style="background:#dfece0">${icon('House')}</div><div class="row-main"><strong>Our apartment</strong><div class="row-sub">3 flatmates · All settled up</div></div>${icon('CheckCheck')}</div><div class="social-callout">${icon('ReceiptText')}Coffee, rent, or a whole weekend.<br>Add it once. Keep everyone in sync.</div>`; }
    function signalHome() { return `${top('Your overview', 'EXPENSE MANAGER / SEPTEMBER')}<div class="hero"><div class="hero-label">MONTH-TO-DATE SPEND<span class="month">Sep 2026 ⌄</span></div><div class="hero-value">₹18,640.00</div><span class="subtle"><span class="positive">↓ 12.0%</span> vs. Aug 1–10 · personal + shared</span></div><div class="chart-card"><div class="chart-header"><span>Daily spending</span><span class="positive">Last 7 days</span></div><div class="bars">${[32, 61, 43, 83, 47, 100, 56].map(n => `<div class="bar" style="height:${n}%"></div>`).join('')}</div><div class="chart-labels">${['04', '05', '06', '07', '08', '09', '10 SEP'].map(n => `<span>${n}</span>`).join('')}</div></div>${summary()}${title('By category', 'Breakdown')}<div class="allocation"><i style="width:42%"></i><i style="width:25%"></i><i style="width:19%"></i><i style="width:14%"></i></div><div class="allocation-legend"><span>Food 42%</span><span>Travel 25%</span><span>Other 33%</span></div>${title('Transactions', 'View all')}${row('Coffee', 'Blue Tokai', '10 Sep · Personal', '−₹280')}${row('Car', 'Uber ride', '10 Sep · Personal', '−₹200')}`; }
    function add(kind) {
        let body = `${formTop()}${segment(kind === 'together')}${amount(kind === 'together' ? '2,400' : '480')}`;
        if (kind === 'together') body += `${field('NotebookPen', 'Dinner at Social')}${field('Users', 'Weekend crew', 'Change')}${field('Utensils', 'Food & drinks', 'Category')}<div class="section-title"><h3 style="font-size:14px">Split equally</h3><span class="text-link">Custom split</span></div><div class="split-people">${[['DP', 'You'], ['AK', 'Arjun'], ['MR', 'Meera'], ['RS', 'Riya']].map(([s, n]) => `<div class="row">${avatar(s, true)}<div class="row-main"><div class="row-title">${n}</div></div><div class="row-amount">₹600.00 ${icon('Check')}</div></div>`).join('')}</div><div class="notification">₹2,400 ÷ 4 people · ₹600 each</div>`;
        else { body += `${categories()}${field('NotebookPen', 'Lunch & coffee', 'Note')}${field('CalendarDays', '10 September 2026', 'Today')}`; if (kind === 'paper') body += `<div class="receipt-note">Small details, a complete picture.<br>This entry is just for you.</div><div class="hint">${icon('Wallet')}Personal expense · No split needed</div>`; else body += keypad(); }
        return body;
    }
    function group(kind) {
        if (kind === 'paper') return `${groupTop()}${cover('The weekend ledger.', 'Weekend crew / Started September 2026', 'NotebookPen')}${balance()}<div class="tabs"><span class="active">Entries</span><span>Balances</span><span>People</span></div><div class="date-label">09 SEPTEMBER / WEDNESDAY</div>${groupRows()}<div class="hint">${icon('CheckCheck')}Every shared expense. In one place.</div>`;
        if (kind === 'together') return `${groupTop()}${cover('Weekend crew', 'The memories are yours. We’ll do the maths.')}${balance()}<div class="tabs"><span class="active">Expenses</span><span>Balances</span><span>Friends</span></div><div class="date-label">YESTERDAY</div>${groupRows()}<div class="notification">You’re all caught up ✨</div>`;
        if (kind === 'signal') return `${groupTop()}${cover('Weekend crew', 'TRIP / SEPTEMBER 2026')}${balance()}<div class="tabs"><span>Activity</span><span class="active">Balances</span><span>Members</span></div>${title('Who owes you', '3 people')}${row('CircleUserRound', 'Arjun', 'Dinner at Social', '₹600.00', 'Owes you', 'positive')}${row('CircleUserRound', 'Meera', 'Dinner at Social', '₹600.00', 'Owes you', 'positive')}${row('CircleUserRound', 'Riya', 'Dinner at Social', '₹600.00', 'Owes you', 'positive')}<div class="hint">${icon('SlidersHorizontal')}Balances include recorded settlements.</div>`;
        return `${groupTop()}${cover()}${balance()}<div class="tabs"><span class="active">Expenses</span><span>Balances</span><span>Members</span></div><div class="date-label">YESTERDAY · 09 SEP</div>${groupRows()}<div class="hint">${icon('Users')}One dinner. Four equal shares. Sorted.</div>`;
    }

    const orbitNav = (active = 'Home') => `<nav class="orbit-nav" aria-label="App navigation"><button class="${active === 'Home' ? 'active' : ''}" data-demo="Home preview">${icon('House')}<span>Home</span></button><button class="${active === 'Activity' ? 'active' : ''}" data-demo="Activity preview">${icon('ReceiptText')}<span>Activity</span></button><button class="orbit-add" data-demo="Open Add expense" aria-label="Add expense">${icon('Plus')}</button><button class="${active === 'Groups' ? 'active' : ''}" data-demo="Groups preview">${icon('Users')}<span>Groups</span></button><button data-demo="Profile preview">${icon('CircleUserRound')}<span>Profile</span></button><div class="homebar"></div></nav>`;
    const orbitHeader = (title = 'Your orbit') => `<div class="orbit-header"><div><span>THU · 10 SEP</span><h2>${title}</h2></div><button data-demo="No new notifications" aria-label="Notifications">${icon('Bell')}<i></i></button></div>`;
    function orbitHome() { return `${orbitHeader()}<div class="orbit-balance"><div class="orbit-ring"><div><small>USED</small><strong>62%</strong></div></div><div><span>September plan</span><h3>₹18,640</h3><p>of ₹30,000</p><div class="orbit-left"><i></i><span>₹11,360 left</span></div></div></div><div class="orbit-actions"><button data-demo="Add expense">${icon('Plus')}Add</button><button data-demo="Settle balances">${icon('CheckCheck')}Settle</button><button data-demo="Open report">${icon('ChartNoAxesCombined')}Report</button></div><div class="orbit-bento"><article><span>YOU ARE OWED</span><strong>₹2,450</strong><small>Across 3 people</small></article><article><span>YOU OWE</span><strong>₹850</strong><small>2 open balances</small></article><article class="wide"><div><span>WEEKEND CREW</span><strong>₹1,800 back</strong><small>4 members · 8 expenses</small></div><div class="orbit-avatars">${avatar('AK', true)}${avatar('MR', true)}${avatar('RS', true)}</div></article></div>${title('Latest motion', 'View all')}${row('Coffee', 'Blue Tokai', 'Today · Food', '−₹280')}${row('Car', 'Uber ride', 'Today · Travel', '−₹200')}`; }
    function orbitAdd() { return `<div class="orbit-form-head"><button class="circle-btn" data-demo="Back to overview">${icon('ArrowLeft')}</button><div><span>QUICK CAPTURE</span><h2>New expense</h2></div><button class="circle-btn" data-demo="Receipt scanner preview">${icon('ReceiptText')}</button></div><div class="orbit-type">${segment()}</div><div class="orbit-amount"><span>AMOUNT · INR</span><div>₹<b data-amount>480</b><small>.00</small></div><p>Tap the amount to edit</p></div><div class="orbit-category-grid">${[['Utensils', 'Food', '42%'], ['Car', 'Travel', '25%'], ['ShoppingBag', 'Shopping', '19%'], ['MoreHorizontal', 'Other', '14%']].map(([i, n, p], x) => `<button class="${x === 0 ? 'selected' : ''}" data-category>${icon(i)}<span>${n}<small>${p} this month</small></span>${icon('Check')}</button>`).join('')}</div>${field('NotebookPen', 'Lunch & coffee', 'Note')}${field('CalendarDays', 'Today, 10 Sep', 'Change')}<div class="orbit-repeat"><span>${icon('Wallet')}Personal expense</span><small>Only you will see this entry</small></div>`; }
    function orbitGroup() { return `<div class="orbit-form-head"><button class="circle-btn" data-demo="Back to groups">${icon('ArrowLeft')}</button><div><span>SHARED SPACE</span><h2>Weekend crew</h2></div><button class="circle-btn" data-demo="Group options">${icon('MoreHorizontal')}</button></div><div class="orbit-group-hero"><div class="orbit-group-title"><span>${icon('Mountain')}</span><div><small>SEP 2026 · 4 PEOPLE</small><h3>One trip.<br>Zero awkward maths.</h3></div></div><div class="orbit-group-total"><span>You get back</span><strong>₹1,800</strong><button data-demo="Settlement preview">Settle up ${icon('ArrowRight')}</button></div></div><div class="orbit-tabs"><button class="selected" data-segment>Activity</button><button data-segment>Balances</button><button data-segment>People</button></div>${title('Today', '3 entries')}${groupRows()}`; }

    const metroNav = (active = 'Month') => `<nav class="metro-nav" aria-label="App navigation">${[['House', 'Month'], ['ReceiptText', 'Trips'], ['Users', 'Groups'], ['CircleUserRound', 'You']].map(([i, n]) => `<button class="${active === n ? 'active' : ''}" data-demo="${n} preview">${icon(i)}<span>${n}</span></button>`).join('')}<button class="metro-add" data-demo="Add expense">${icon('Plus')}</button><div class="homebar"></div></nav>`;
    const metroTop = (title = 'Your month') => `<div class="metro-top"><div><span>EXPENSE LINE · SEP 2026</span><h2>${title}</h2></div><button data-demo="Month options">${icon('MoreHorizontal')}</button></div>`;
    const station = (color, titleText, sub, amt, terminal = false) => `<div class="metro-station ${terminal ? 'terminal' : ''}" style="--station:${color}"><span><i></i></span><div><strong>${titleText}</strong><small>${sub}</small></div><b>${amt}</b></div>`;
    function metroHome() { return `${metroTop()}<div class="metro-fare"><span>MONTH-TO-DATE</span><strong>₹18,640</strong><small>12% below last month’s route</small><div class="metro-lines"><i></i><i></i><i></i><i></i></div></div><div class="metro-balances"><div><span class="dot aqua"></span><small>TO RECEIVE</small><strong>₹2,450</strong></div><div><span class="dot orange"></span><small>TO PAY</small><strong>₹850</strong></div></div><div class="metro-route-head"><span>TODAY’S ROUTE</span><button data-demo="See full activity">All stations</button></div><div class="metro-route">${station('#55c6b5', 'Blue Tokai', '09:18 · Food & drinks', '−₹280')}${station('#f56b3a', 'Uber ride', '08:42 · Travel', '−₹200')}${station('#f2c94c', 'Dinner at Social', 'Yesterday · Shared', '−₹600', true)}</div><div class="metro-alert">${icon('TrendingDown')} Next checkpoint: ₹20,000 monthly spend</div>`; }
    function metroAdd() { return `<div class="metro-form-top"><button data-demo="Back to month">${icon('ArrowLeft')}<span>Month</span></button><strong>New stop</strong><button data-demo="Close expense">${icon('X')}</button></div><div class="metro-ticket"><span>FARE / INR</span><div>₹<b data-amount>480</b><small>.00</small></div><p>PERSONAL LINE · TODAY</p></div><div class="metro-line-picker">${[['#55c6b5', 'Utensils', 'Food'], ['#f56b3a', 'Car', 'Travel'], ['#f2c94c', 'ShoppingBag', 'Shop'], ['#9b8cd6', 'MoreHorizontal', 'Other']].map(([c, i, n], x) => `<button class="${x === 0 ? 'selected' : ''}" style="--pick:${c}" data-category><span>${icon(i)}</span>${n}</button>`).join('')}</div><div class="metro-fields">${field('NotebookPen', 'Lunch & coffee', 'Edit')}${field('CalendarDays', '10 September', 'Today')}${field('Wallet', 'Personal expense', 'Change')}</div><div class="metro-keypad">${['1', '2', '3', '4', '5', '6', '7', '8', '9', '.', '0', 'Delete'].map(n => `<button data-key="${n}">${n === 'Delete' ? icon(n) : n}</button>`).join('')}</div>`; }
    function metroGroup() { return `${metroTop('Weekend route')}<div class="metro-group-line"><div class="metro-line-name"><span>W4</span><div><small>WEEKEND CREW</small><h3>₹1,800 to receive</h3></div></div><div class="metro-member-stops"><span>YOU</span><i></i><span>AK</span><i></i><span>MR</span><i></i><span>RS</span></div><button data-demo="Settle group">Settle route ${icon('ArrowRight')}</button></div><div class="metro-route-head"><span>WEDNESDAY · 9 SEP</span><button data-demo="Group balances">Balances</button></div><div class="metro-route metro-group-route">${station('#55c6b5', 'Dinner at Social', 'You paid ₹2,400 · Split four ways', '+₹1,800')}${station('#f56b3a', 'Cab back home', 'Arjun paid · Settled', '₹200')}${station('#f2c94c', 'Coffee catch-up', 'Meera paid · Settled', '₹150', true)}</div><div class="metro-key"><span><i style="background:#55c6b5"></i>Food</span><span><i style="background:#f56b3a"></i>Travel</span><span><i style="background:#f2c94c"></i>Shared</span></div>`; }

    const cashNav = (active = 'Home') => `<nav class="cash-nav">${[['House', 'Home'], ['ReceiptText', 'Log'], ['Plus', 'Add'], ['Users', 'Groups'], ['CircleUserRound', 'You']].map(([i, n]) => `<button class="${active === n ? 'active' : ''} ${n === 'Add' ? 'cash-add' : ''}" data-demo="${n} preview">${icon(i)}<span>${n}</span></button>`).join('')}<div class="homebar"></div></nav>`;
    const cashTop = (group = false) => `<div class="cash-top">${group ? `<button data-demo="Back to groups">${icon('ArrowLeft')}</button>` : '<span>@dhairya</span>'}<button data-demo="Options">${group ? icon('MoreHorizontal') : 'DP'}</button></div>`;
    function cashHome() { return `${cashTop()}<div class="cash-owed"><span>YOU'RE OWED</span><strong>₹2,450</strong></div><div class="cash-brand"><div><b>SPLITTRACK</b><small>@dhairya · you owe ₹850</small></div>${icon('Wallet')}</div><div class="cash-label"><span>ACTIVITY</span><button data-demo="See all activity">See all</button></div><div class="cash-list">${row('Coffee', 'Blue Tokai', 'Today', '−₹280')}${row('Utensils', 'Dinner at Social', 'Yesterday', '+₹1,800', '', 'positive')}${row('Car', 'Uber ride', 'Monday', '−₹200')}</div><div class="cash-bar"><span>NET POSITION</span><strong>+₹1,600</strong></div>`; }
    function cashAdd() { return `<div class="cash-add-top"><button data-demo="Close">${icon('X')}</button><span>FOR WEEKEND CREW</span><i></i></div><div class="cash-big-amount">₹<b data-amount>480</b></div><div class="cash-categories">${[['Utensils', 'Food'], ['Car', 'Travel'], ['ShoppingBag', 'Shop'], ['MoreHorizontal', 'Other']].map(([i, n], x) => `<button class="${x === 0 ? 'selected' : ''}" data-category>${icon(i)}${n}</button>`).join('')}</div><div class="cash-keypad">${['1', '2', '3', '4', '5', '6', '7', '8', '9', '.', '0', 'Delete'].map(n => `<button data-key="${n}">${n === 'Delete' ? icon(n) : n}</button>`).join('')}</div><div class="cash-note">${icon('NotebookPen')} Dinner at Social</div>`; }
    function cashGroup() { return `${cashTop(true)}<div class="cash-group-title"><h2>WEEKEND<br>CREW</h2><span>4 people · started Sep 2026</span><div>${avatar('DP', true)}${avatar('AK', true)}${avatar('MR', true)}${avatar('RS', true)}</div></div><div class="cash-owed group"><span>YOU'RE OWED</span><strong>₹1,800</strong></div><button class="cash-settle" data-demo="Settle up">SETTLE UP</button><div class="cash-tabs"><button class="selected" data-segment>ACTIVITY</button><button data-segment>BALANCES</button></div><div class="cash-list">${row('Utensils', 'Dinner at Social', 'You paid ₹2,400', '+₹1,800', '', 'positive')}${row('Car', 'Cab back home', 'Arjun paid · Settled', '₹200')}${row('Coffee', 'Coffee catch-up', 'Meera paid · Settled', '₹150')}</div>`; }

    const duoNav = (active = 'Home') => `<nav class="duo-nav">${[['House', 'Home'], ['ReceiptText', 'History'], ['Plus', 'Add'], ['Users', 'Groups'], ['CircleUserRound', 'You']].map(([i, n]) => `<button class="${active === n ? 'active' : ''} ${n === 'Add' ? 'duo-add' : ''}" data-demo="${n} preview">${icon(i)}<span>${n}</span></button>`).join('')}<div class="homebar"></div></nav>`;
    function duoHome() { return `<div class="duo-head"><span>${icon('TrendingDown')} 4-day streak</span><button data-demo="Profile">DP</button></div><div class="duo-streak"><span>NO-SPLURGE DAYS THIS MONTH</span><strong>18/30</strong><div>${Array.from({ length: 7 }, (_, i) => `<i class="${i < 4 ? 'done' : ''}">${i < 4 ? '✓' : i + 1}</i>`).join('')}</div></div><div class="duo-balances"><article><span>OWED TO YOU</span><strong>₹2,450</strong></article><article><span>YOU OWE</span><strong>₹850</strong></article></div><div class="duo-section">Recent</div><div class="duo-list">${row('Coffee', 'Blue Tokai', 'Today', '₹280')}${row('Utensils', 'Dinner at Social', 'Yesterday', '₹600')}${row('Car', 'Uber ride', 'Monday', '₹200')}</div><div class="duo-cheer">${icon('CheckCheck')} Nice! You logged every expense this week.</div>`; }
    function duoAdd() { return `<div class="duo-form-top"><button data-demo="Close">${icon('X')}</button><strong>What'd you spend?</strong><i></i></div><div class="duo-mode"><button class="selected" data-segment>Solo</button><button data-segment>Friend</button><button data-segment>Group</button></div><div class="duo-amount">₹<b data-amount>480</b></div><div class="duo-category-grid">${[['Utensils', 'Food'], ['Car', 'Travel'], ['ShoppingBag', 'Shop'], ['MoreHorizontal', 'Other']].map(([i, n], x) => `<button class="${x === 0 ? 'selected' : ''}" data-category>${icon(i)}<span>${n}</span></button>`).join('')}</div>${field('NotebookPen', 'Lunch & coffee', 'Note')}${field('CalendarDays', 'Today', 'Change')}<div class="duo-tip">Logging takes less than 10 seconds.</div>`; }
    function duoGroup() { return `<div class="duo-form-top"><button data-demo="Back">${icon('ArrowLeft')}</button><strong>Weekend crew</strong><button data-demo="Options">${icon('MoreHorizontal')}</button></div><div class="duo-people">${avatar('DP', true)}${avatar('AK', true)}${avatar('MR', true)}${avatar('RS', true)}</div><div class="duo-ahead"><span>WHO'S AHEAD</span><div><i></i><b></b></div><small><em>You're owed ₹1,800</em><em>You owe ₹0</em></small></div><button class="duo-settle" data-demo="Settle up">Settle up</button><div class="duo-section">Activity</div><div class="duo-list">${row('Utensils', 'Dinner at Social', 'You paid ₹2,400', '+₹1,800', '', 'positive')}${row('Car', 'Cab back home', 'Arjun paid · Settled', '₹200')}${row('Coffee', 'Coffee catch-up', 'Meera paid · Settled', '₹150')}</div>`; }

    const sproutNav = (active = 'Rhythm') => `<nav class="sprout-nav">${[['CalendarDays', 'Rhythm'], ['ReceiptText', 'Journal'], ['Users', 'Shared'], ['ChartNoAxesCombined', 'Insight']].map(([i, n]) => `<button class="${active === n ? 'active' : ''}" data-demo="${n} preview">${icon(i)}<span>${n}</span></button>`).join('')}<button class="sprout-add" data-demo="Add expense">${icon('Plus')}</button><div class="homebar"></div></nav>`;
    function sproutHome() { return `<div class="sprout-head"><div><span>SEPTEMBER RHYTHM</span><h2>Keep it clear,<br>day by day.</h2></div><button data-demo="Profile">DP</button></div><div class="sprout-days">${['M', 'T', 'W', 'T', 'F', 'S', 'S'].map((d, i) => `<div class="${i < 4 ? 'done' : ''}"><i>${i < 4 ? '✓' : i + 1}</i><span>${d}</span></div>`).join('')}</div><div class="sprout-budget"><div><span>MONTHLY PACE</span><strong>₹11,360 left</strong><small>62% of plan used</small></div><div class="sprout-ring">62</div></div><div class="sprout-summary"><span>₹2,450 to receive</span><span>₹850 to pay</span></div><div class="sprout-section">This week <button data-demo="See month">See month</button></div>${row('Coffee', 'Blue Tokai', 'Today · Food', '₹280')}${row('Car', 'Uber ride', 'Today · Travel', '₹200')}${row('Utensils', 'Dinner at Social', 'Yesterday · Shared', '₹600')}`; }
    function sproutAdd() { return `<div class="sprout-form-top"><button data-demo="Back">${icon('ArrowLeft')}</button><div><span>THURSDAY'S ENTRY</span><h2>Add to journal</h2></div><button data-demo="Close">${icon('X')}</button></div><div class="sprout-amount"><span>How much?</span><div>₹<b data-amount>480</b><small>.00</small></div></div><div class="sprout-mode"><button class="selected" data-segment>Personal</button><button data-segment>Friend</button><button data-segment>Group</button></div><div class="sprout-categories">${[['Utensils', 'Food'], ['Car', 'Travel'], ['ShoppingBag', 'Shop'], ['MoreHorizontal', 'Other']].map(([i, n], x) => `<button class="${x === 0 ? 'selected' : ''}" data-category>${icon(i)}<span>${n}</span></button>`).join('')}</div>${field('NotebookPen', 'Lunch & coffee', 'Note')}${field('CalendarDays', 'Today, 10 Sep', 'Change')}<div class="sprout-private">${icon('Check')} This keeps your four-day logging rhythm going.</div>`; }
    function sproutGroup() { return `<div class="sprout-form-top"><button data-demo="Back">${icon('ArrowLeft')}</button><div><span>SHARED RHYTHM</span><h2>Weekend crew</h2></div><button data-demo="Options">${icon('MoreHorizontal')}</button></div><div class="sprout-group"><span>Clear between friends</span><strong>₹1,800</strong><small>coming back to you</small><div>${people()}</div><button data-demo="Settle group">Settle gently</button></div><div class="sprout-section">Wednesday <button data-demo="Balances">Balances</button></div>${groupRows()}<div class="sprout-private">${icon('CheckCheck')} All four shares have been recorded.</div>`; }

    const sproutDarkNav = (active = 'Rhythm') => `<nav class="sprout-dark-nav">${[['CalendarDays', 'Rhythm'], ['ReceiptText', 'Journal'], ['Users', 'Shared'], ['ChartNoAxesCombined', 'Insight']].map(([i, n]) => `<button class="${active === n ? 'active' : ''}" data-demo="${n} preview">${icon(i)}<span>${n}</span></button>`).join('')}<button class="sprout-dark-add" data-demo="Add expense" aria-label="Add expense">${icon('Plus')}</button><div class="homebar"></div></nav>`;
    const darkFormTop = (eyebrow, title, right = 'X') => `<div class="dark-form-top"><button data-demo="Back">${icon('ArrowLeft')}</button><div><span>${eyebrow}</span><h2>${title}</h2></div><button data-demo="Close">${icon(right)}</button></div>`;
    const darkCategories = () => `<div class="dark-categories">${[['Utensils', 'Food'], ['Car', 'Travel'], ['ShoppingBag', 'Shop'], ['MoreHorizontal', 'Other']].map(([i, n], x) => `<button class="${x === 0 ? 'selected' : ''}" data-category>${icon(i)}<span>${n}</span></button>`).join('')}</div>`;

    function sproutNightHome() { return `<div class="dark-top"><div><span>THURSDAY / 10 SEP</span><h2>Your evening<br>check-in.</h2></div><button data-demo="Profile">DP</button></div><div class="night-week"><div><span>MON</span><i>✓</i></div><div><span>TUE</span><i>✓</i></div><div><span>WED</span><i>✓</i></div><div class="today"><span>THU</span><i>10</i></div><div><span>FRI</span><i>11</i></div><div><span>SAT</span><i>12</i></div><div><span>SUN</span><i>13</i></div></div><div class="night-pace"><div><span>SEPTEMBER PACE</span><strong>₹11,360</strong><small>still free for the month</small></div><div class="night-orbit"><b>62</b><small>%</small></div></div><div class="dark-split"><span>${icon('ArrowDownLeft')} ₹2,450 incoming</span><span>${icon('ArrowUpRight')} ₹850 outgoing</span></div><div class="dark-section">Today’s ledger <button data-demo="See journal">See journal</button></div>${row('Coffee', 'Blue Tokai', '21:18 · Food', '−₹280')}${row('Car', 'Uber ride', '18:42 · Travel', '−₹200')}`; }
    function sproutNightAdd() { return `${darkFormTop('QUIETLY LOG IT', 'New journal entry')}<div class="dark-amount"><span>Amount</span><div>₹<b data-amount>480</b><small>.00</small></div></div><div class="dark-mode"><button class="selected" data-segment>Personal</button><button data-segment>Friend</button><button data-segment>Group</button></div>${darkCategories()}${field('NotebookPen', 'Dinner on the way home', 'Note')}${field('CalendarDays', 'Tonight · 10 September', 'Change')}<div class="dark-confirm">${icon('Check')} One clear entry, one calmer tomorrow.</div>`; }
    function sproutNightGroup() { return `${darkFormTop('SHARED AFTER DARK', 'Weekend crew', 'MoreHorizontal')}<div class="night-group"><span>YOU’RE DUE BACK</span><strong>₹1,800</strong><p>Arjun, Meera, and Riya each owe ₹600.</p><div>${people()}</div><button data-demo="Settle group">Send gentle reminder</button></div><div class="dark-section">Wednesday <button data-demo="Balances">Balances</button></div>${groupRows()}<div class="dark-confirm">${icon('CheckCheck')} Three earlier shares are settled.</div>`; }

    function sproutMoonHome() { return `<div class="moon-head"><div><span>SEPTEMBER / LOW TIDE</span><h2>Spend with<br>the lights low.</h2></div><button data-demo="Profile">DP</button></div><div class="moon-meter"><div class="moon-meter-copy"><span>MONTHLY SPEND</span><strong>₹18,640</strong><small>₹11,360 remains before your comfort line</small></div><div class="moon-arc"><b>62</b><small>%</small></div></div><div class="moon-days">${['M', 'T', 'W', 'T', 'F', 'S', 'S'].map((d, i) => `<div class="${i < 4 ? 'done' : ''}"><i>${i < 3 ? '✓' : i === 3 ? '10' : i + 7}</i><span>${d}</span></div>`).join('')}</div><div class="moon-note">${icon('Check')} Four days in a row. The record is enough.</div><div class="dark-section">Small things, noted <button data-demo="View month">View month</button></div>${row('Coffee', 'Blue Tokai', 'Today · Food', '₹280')}${row('Utensils', 'Dinner at Social', 'Yesterday · Shared', '₹600')}${row('Car', 'Uber ride', 'Yesterday · Travel', '₹200')}`; }
    function sproutMoonAdd() { return `${darkFormTop('A SMALL RECORD', 'What moved today?')}<div class="moon-entry"><span>INR</span><div>₹<b data-amount>480</b></div><small>It can be approximate. You can refine it later.</small></div><div class="moon-pills"><button class="selected" data-segment>Just me</button><button data-segment>With a friend</button><button data-segment>With a group</button></div>${darkCategories()}${field('NotebookPen', 'Lunch & coffee', 'Add note')}${field('CalendarDays', '10 Sep · Tonight', 'Change')}<div class="moon-save">${icon('Check')} Keep the day in view</div>`; }
    function sproutMoonGroup() { return `${darkFormTop('THE PEOPLE YOU SHARE WITH', 'Weekend crew', 'MoreHorizontal')}<div class="moon-group"><div><span>GROUP BALANCE</span><strong>₹1,800</strong><small>coming back to you</small></div><div class="moon-people">${avatar('DP', true)}${avatar('AK', true)}${avatar('MR', true)}${avatar('RS', true)}</div><button data-demo="Settle group">Review what’s open ${icon('ArrowRight')}</button></div><div class="dark-section">Latest shared notes <button data-demo="Balances">Balances</button></div>${groupRows()}<div class="moon-note">${icon('Check')} No rush—everything is visible here.</div>`; }

    function sproutEmberHome() { return `<div class="ember-head"><span>SPRING / AFTER HOURS</span><button data-demo="Profile">DP</button></div><h2>Money, without<br>the noise.</h2><div class="ember-total"><span>THIS MONTH</span><strong>₹18,640</strong><small>Personal and shared spending</small><div><i style="width:62%"></i></div><b>62% of comfort pace</b></div><div class="ember-counters"><article><span>TO RECEIVE</span><strong>₹2,450</strong></article><article><span>TO PAY</span><strong>₹850</strong></article></div><div class="dark-section">Recent movement <button data-demo="All activity">All activity</button></div>${row('Utensils', 'Dinner at Social', 'Yesterday · Weekend crew', '+₹1,800', 'You paid', 'positive')}${row('Coffee', 'Blue Tokai', 'Today · Food', '−₹280')}`; }
    function sproutEmberAdd() { return `${darkFormTop('ADD, THEN LET IT GO', 'New expense')}<div class="ember-amount"><span>HOW MUCH?</span><div>₹<b data-amount>480</b></div></div><div class="ember-kind"><button class="selected" data-segment>PERSONAL</button><button data-segment>FRIEND</button><button data-segment>GROUP</button></div>${darkCategories()}${field('NotebookPen', 'Lunch & coffee', 'Note')}${field('CalendarDays', 'Today, 10 Sep', 'Change')}<div class="ember-tip">${icon('Check')} Your four-day rhythm stays intact.</div>`; }
    function sproutEmberGroup() { return `${darkFormTop('SHARED LEDGER', 'Weekend crew', 'MoreHorizontal')}<div class="ember-group"><span>NET POSITION</span><strong>+₹1,800</strong><small>You covered dinner. Three people owe ₹600.</small><div>${people()}</div><button data-demo="Settle group">Settle the balance</button></div><div class="dark-section">Group activity <button data-demo="Balances">Balances</button></div>${groupRows()}<div class="ember-tip">${icon('CheckCheck')} Clear accounts make room for the next plan.</div>`; }

    const stackNav = (active = 'STACK') => `<nav class="stack-nav">${[['Wallet', 'STACK'], ['Plus', 'ADD'], ['Users', 'PEOPLE'], ['ChartNoAxesCombined', 'STATS']].map(([i, n]) => `<button class="${active === n ? 'active' : ''}" data-demo="${n} preview">${icon(i)}<span>${n}</span></button>`).join('')}<div class="homebar"></div></nav>`;
    function stackHome() { return `<div class="stack-head"><span>YOUR MONEY / 10 SEP</span><button data-demo="Profile">DP</button></div><h2 class="stack-title">Your stack.</h2><div class="stack-cards"><article><span>PERSONAL / SEP</span><strong>₹18,640</strong><small>spent this month</small></article><article><span>SHARED / NET</span><strong>+₹1,600</strong><small>coming back to you</small></article><article><span>WEEKEND CREW</span><strong>+₹1,800</strong><small>4 people · 8 expenses</small></article></div><div class="stack-label">RECENT BY LAYER <button data-demo="Filter">FILTER</button></div>${row('Coffee', 'Blue Tokai', 'Personal · Today', '−₹280')}${row('Utensils', 'Dinner at Social', 'Weekend crew · Yesterday', '+₹1,800', '', 'positive')}`; }
    function stackAdd() { return `<div class="stack-head"><button data-demo="Back">${icon('ArrowLeft')}</button><span>ADD TO STACK</span><button data-demo="Close">${icon('X')}</button></div><div class="stack-sheets"><button class="selected" data-segment>PERSONAL</button><button data-segment>FRIEND</button><button data-segment>GROUP</button></div><div class="stack-amount"><span>AMOUNT / INR</span><div>₹<b data-amount>480</b></div></div><div class="stack-details">${field('NotebookPen', 'Lunch & coffee', 'Note')}${field('Utensils', 'Food & drinks', 'Category')}${field('CalendarDays', '10 September', 'Today')}</div><div class="stack-categories">${[['Utensils', 'FOOD'], ['Car', 'TRAVEL'], ['ShoppingBag', 'SHOP'], ['MoreHorizontal', 'OTHER']].map(([i, n], x) => `<button class="${x === 0 ? 'selected' : ''}" data-category>${icon(i)}${n}</button>`).join('')}</div>`; }
    function stackGroup() { return `<div class="stack-head"><button data-demo="Back">${icon('ArrowLeft')}</button><span>GROUP LAYER</span><button data-demo="Options">${icon('MoreHorizontal')}</button></div><h2 class="stack-title">Weekend<br>crew.</h2><div class="stack-group-card"><span>GROUP BALANCE</span><strong>+₹1,800</strong><small>You are owed</small><button data-demo="Settle group">SETTLE</button></div><div class="stack-people">${avatar('DP', true)}${avatar('AK', true)}${avatar('MR', true)}${avatar('RS', true)}<span>4 PEOPLE</span></div><div class="stack-label">GROUP ACTIVITY <button data-demo="Balances">BALANCES</button></div>${groupRows()}`; }

    const concepts = [
        { id: 'emerald', name: 'Emerald', tag: 'FAMILIAR / FOCUSED / REASSURING', description: 'An evolution of your current app. Rich charcoal, emerald highlights, and a clear daily spending overview.', home: emeraldHome, third: 'Group activity' },
        { id: 'paper', name: 'Paper', tag: 'CALM / TACTILE / CONSIDERED', description: 'A quieter place for money. Warm paper tones, open layouts, and a personal ledger you’ll want to return to.', home: paperHome, third: 'Shared ledger' },
        { id: 'together', name: 'Together', tag: 'SOCIAL / EXPRESSIVE / FRIENDLY', description: 'Made for shared lives. People come first, splits feel simple, and every group has a little personality.', home: togetherHome, third: 'Group activity' },
        { id: 'signal', name: 'Signal', tag: 'PRECISE / COMPACT / INSIGHTFUL', description: 'The numbers, beautifully organized. Crisp charts, tabular amounts, and balances you can scan in seconds.', home: signalHome, third: 'Group balances' },
        { id: 'orbit', name: 'Orbit', tag: 'BOLD / MODULAR / ENERGETIC', description: 'A bright bento workspace for money in motion. Plan progress, shortcuts, and shared balances stay within reach.', home: orbitHome, add: orbitAdd, group: orbitGroup, third: 'Shared space', homeFooter: () => orbitNav(), groupFooter: () => orbitNav('Groups') },
        { id: 'metro', name: 'Metro', tag: 'WAYFINDING / CONNECTED / QUICK', description: 'A route-map model connects categories, transactions, and shared expenses using consistent line colors.', home: metroHome, add: metroAdd, group: metroGroup, third: 'Weekend route', homeFooter: () => metroNav(), groupFooter: () => metroNav('Groups'), size: [393, 852] },
        { id: 'cashcoded', name: 'Cashcoded', tag: 'SUPPLIED / BOLD / CASH-FIRST', description: 'Your black-and-signal-orange reference, rebuilt at full iPhone scale with its oversized receivable balance intact.', home: cashHome, add: cashAdd, group: cashGroup, third: 'Group detail', homeFooter: () => cashNav(), groupFooter: () => cashNav('Groups'), addFooter: () => formFoot('SPLIT IT'), size: [393, 852] },
        { id: 'duostreak', name: 'Duo Streak', tag: 'SUPPLIED / MOTIVATING / TACTILE', description: 'Your cream, green, and orange reference, preserving streak progress, outlined tiles, and satisfying pressed actions.', home: duoHome, add: duoAdd, group: duoGroup, third: 'Group detail', homeFooter: () => duoNav(), groupFooter: () => duoNav('Groups'), addFooter: () => formFoot('LOG IT!'), size: [393, 852] },
        { id: 'sprout', name: 'Sprout', tag: 'ENCOURAGING / CALM / CONSISTENT', description: 'A grown-up evolution of streak tracking that rewards record-keeping consistency and healthy budget pace.', home: sproutHome, add: sproutAdd, group: sproutGroup, third: 'Shared rhythm', homeFooter: () => sproutNav(), groupFooter: () => sproutNav('Shared'), size: [393, 852] },
        { id: 'stack', name: 'Stack', tag: 'LAYERED / SOCIAL / STRUCTURED', description: 'Personal, friend, and group expenses become persistent visual layers with their own colors and hierarchy.', home: stackHome, add: stackAdd, group: stackGroup, third: 'Group layer', homeFooter: () => stackNav(), groupFooter: () => stackNav('PEOPLE'), addFooter: () => formFoot('ADD TO STACK'), size: [393, 852] },
        { id: 'sprout-night', name: 'Sprout Night', tag: 'FOREST / GOLD / REASSURING', description: 'Sprout shifted into a low-light evening check-in: warm gold makes the pace legible while leaf green holds the completed rhythm.', home: sproutNightHome, add: sproutNightAdd, group: sproutNightGroup, third: 'Shared after dark', homeFooter: () => sproutDarkNav(), groupFooter: () => sproutDarkNav('Shared'), size: [393, 852] },
        { id: 'sprout-moon', name: 'Sprout Moon', tag: 'BLUE-GREEN / SILVER / REFLECTIVE', description: 'A cooler, quieter Sprout for end-of-day reflection, built around gentle prompts and an uncluttered view of shared balances.', home: sproutMoonHome, add: sproutMoonAdd, group: sproutMoonGroup, third: 'Shared under moonlight', homeFooter: () => sproutDarkNav(), groupFooter: () => sproutDarkNav('Shared'), size: [393, 852] },
        { id: 'sprout-ember', name: 'Sprout Ember', tag: 'CHARCOAL / CLAY / DIRECT', description: 'A more editorial dark mode: strong type and restrained clay signals make an after-hours money check feel clear and grounded.', home: sproutEmberHome, add: sproutEmberAdd, group: sproutEmberGroup, third: 'Shared ledger', homeFooter: () => sproutDarkNav(), groupFooter: () => sproutDarkNav('Shared'), size: [393, 852] }
    ];
    document.getElementById('designs').innerHTML = concepts.map((c, i) => { const [w, h] = c.size || [390, 844]; return `<section class="concept ${c.id}-board" id="${c.id}"><div class="board-heading"><div class="board-title"><span class="board-number">${String(i + 1).padStart(2, '0')}</span><div><h2>${c.name}</h2><p class="subtitle">${c.tag}</p></div></div><p>${c.description}</p></div><div class="screens">${[['Overview', c.home(), c.homeFooter ? c.homeFooter() : nav()], ['Add expense', c.add ? c.add() : add(c.id), c.addFooter ? c.addFooter() : formFoot(c.id === 'together' ? 'Save & split expense' : 'Save expense')], [c.third, c.group ? c.group() : group(c.id), c.groupFooter ? c.groupFooter() : nav('Groups')]].map(([n, b, f], j) => `<div class="screen-wrap" style="width:${w}px"><article class="phone ${c.id}" style="width:${w}px;height:${h}px" id="${c.id}-${j + 1}" aria-label="${c.name} — ${n}">${status()}<div class="content">${b}</div>${f}</article><div class="screen-caption"><span>0${j + 1} / ${n.toUpperCase()}</span><span>${w} × ${h}</span></div></div>`).join('')}</div></section>` }).join('');
    document.addEventListener('click', e => { const b = e.target.closest('button'); if (!b) return; const phone = b.closest('.phone'); if (!phone) return; if (b.hasAttribute('data-segment') || b.hasAttribute('data-category')) { b.parentElement.querySelectorAll('.selected').forEach(x => x.classList.remove('selected')); b.classList.add('selected'); } if (b.dataset.key) { const el = phone.querySelector('[data-amount]'); let v = el.textContent.replaceAll(',', ''); v = b.dataset.key === 'Delete' ? v.slice(0, -1) : v.length < 9 && !(b.dataset.key === '.' && v.includes('.')) ? v + b.dataset.key : v; el.textContent = v || '0'; } if (b.dataset.demo || b.hasAttribute('data-save')) { phone.querySelector('.toast')?.remove(); const toast = document.createElement('div'); toast.className = 'toast'; toast.setAttribute('role', 'status'); toast.textContent = b.hasAttribute('data-save') ? 'Design preview · Expense saved (sample only)' : b.dataset.demo; phone.append(toast); setTimeout(() => toast.remove(), 2700); } });
    const exportId = new URLSearchParams(location.search).get('export'); if (concepts.some(x => x.id === exportId)) { document.body.classList.add('export-mode'); document.getElementById(exportId).classList.add('export-active'); }

})();
